public:
    secrets:
        data:
            DB_PASSWORD: ENC[AES256_GCM,data:OQx8/Cmz248ayvdwVdkNVR1KZJnfy0J/3zicX4TMlvxJDeACcMOsIskmio8=,iv:ZG72YxXBkRKIL7tpaF/NwgU+9D+pl8cWVwDB+JipO3A=,tag:P5TvdWGHUoocVjA23hwjrw==,type:str]
            JWT_SECRET: ENC[AES256_GCM,data:dpS/iMHjipR00Ob5xIuA8XpQsx32HdOeQLrvU89vvCCLSRkvPUpP+0DpxT8=,iv:pCsAQPxHhIj/yJ4p7euE5u8L2gR+JlOtTq0GJkSN9AE=,tag:ZqqhvPaxE73yIrOIvKdQwQ==,type:str]
            CERT_PASS: ""
            DOMAIN: ""
            HOME_PAGE_URL: ""
gateway:
    env:
        - name: ENC[AES256_GCM,data:gZSjzeTSIH9mZg==,iv:NIwpYC8X5YSykeLovTZAGamYk1pCcTZ9zORjElMArk0=,tag:BJUww7hxoHIxmgchf2kz5Q==,type:str]
          value: ENC[AES256_GCM,data:+iV1mQE+iw5RCOSCfojNIG5RMAH9x+0PBAwNYpEKFvTmUfDvjCEi1ykQW6o=,iv:0mUP/BPYpHB2bvKfQZ15TeaICe3uJdu8EobL8M6DHtg=,tag:9e1QjigvK+cF6eSMZJ3s3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNmNZdFJJN2JkaGFVM1lt
            K2x5dFNaV3czUVduRlY4aHY2U2JlZVZFbWtvCnlPdHhWcElKS2FQbFJ5cnpMQ0tL
            VjhiRjlRK002OEt3UUtSanppZVJCcUEKLS0tIHJVUDF1SU5TZC9qUmlZRGdMZjht
            M1I2STNoKzdteXNFTUdVczdsSFY5bUkKblFkFp2073nMZgkpqug9wrrbso14HZAk
            ZLzSwQBYtcV1103ri/pGFAyWWqIboAZ3Ki4BIprymRvlX+2XVtqCog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19lksug4t4qtjkak824m0d48d75nyx26p5mgv83yetnupu3w2fq3sx8kxdm
    lastmodified: "2026-05-25T03:07:14Z"
    mac: ENC[AES256_GCM,data:iHn7oK3+kUnEZ0f2gYbZF+VloKSYNBcDpFTCP7SEGoXo7RiaGIg3EEj0OfOjlNJq7nLhZorRCq9ewjyhh5K3guW0Ys2Mh8hPrD1FEmw2kkiDzuzQA0qhx6DT7uXTyrhn1QyhvLwWrqMP+8jYjayLfNqMvYWpg5KYFi76MPVi/sE=,iv:SCQ3s/QNL+QILV1517vm3944rvCJU/9I92NGXxGO3tQ=,tag:I8fJVVCT46ygmyuus23+yw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
