public:
    secrets:
        data:
            DB_PASSWORD: ENC[AES256_GCM,data:vX907qq/Iu/1v2IWAXYKKN9P2PkFC992GyF1fZT1gmmLdyfWtkARTbmHgqM=,iv:wHWaaQT5m9a34LN9NZiEOxrtwtUnd4y056h6WxlurYc=,tag:7inilRxi9QJY2slkF6P9jg==,type:str]
            CERT_PASS: ""
            DOMAIN: ""
            HOME_PAGE_URL: ""
gateway:
    env:
        - name: ENC[AES256_GCM,data:yvymNzt7F3oJPA==,iv:JPJOJ+y4dvnXNQYpchL66MRNNrxidMTxyfEgbi30tpA=,tag:mJ9aPHXR61ybkNvpIxqJfw==,type:str]
          value: ENC[AES256_GCM,data:om/hHL6wx7Bp2Xud2Te/jsOC8jakLCJOfzeuyZqGxjutK66+v//kjjnkTkY=,iv:WUvXTmTSfEZh4aOMRhtFH1ceRsuwtnm8pv9/qxG8K0U=,tag:pqUJhS+HYtsmBQqKXq5nJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVY2ekE4RWZta3ZIdTVm
            eXZTOXViaUpxUGlSNjAyUVk4M2NpZ1lBVWs0ClJMaUVPRXMxbW9OU3F1T0kxSlA0
            VENSZ0o2MW9GTmVQSWwyT0h0cFJoWUUKLS0tIHZGcHZzWTArK01DbVBJc21Ib2ZD
            cnpCK01CZkdEaUJVS0NpVUc1NFlHTm8KZcEMm+q1Y4Zb0XJ28soc+cuPluejOs28
            WRB9Jde2Ext6b4LN05ZJ/BkH0LZPYneB7ZhuN+a2o1p2Xc3bjZrO5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19lksug4t4qtjkak824m0d48d75nyx26p5mgv83yetnupu3w2fq3sx8kxdm
    lastmodified: "2026-05-22T08:19:22Z"
    mac: ENC[AES256_GCM,data:y9aHJfy+QXoNnIUcrdtiubMKAS4JiyAKFE33M3/2REz4D+v/9AKV258c2Q3U7BjGZOaW3wgv0CGbaHWurmYZ5xjwemv6Ev60ozt1Oy3BG9fG29ckcQooeNT/FiavjFJ7Xw72Kyj1mgDf+4cgfbNn5Wdqa9TF15o0vTnBxjC7v00=,iv:7xIH0txZCT/zuBFqrzOcESNice8QAlAzDK7dEqmSn/w=,tag:TPI6at/w+xKLkLvCvgMKHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
