apiVersion: v1
kind: Service
metadata:
  name: datamate-runtime
  labels:
    ray.io/node-type: head
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    ray.io/node-type: head

