apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamate-frontend
  labels:
    app: datamate
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamate
      tier: frontend
  template:
    metadata:
      labels:
        app: datamate
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: datamate-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/datamate/frontend
              subPath: frontend
      volumes:
        - name: log-volume
          hostPath:
            path: /opt/datamate/data/log
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: datamate-frontend
  labels:
    app: datamate
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  selector:
    app: datamate
    tier: frontend
