name: Frontend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'scripts/images/frontend/**'
      - '.github/workflows/docker-image-frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'scripts/images/frontend/**'
      - '.github/workflows/docker-image-frontend.yml'
  workflow_dispatch:

jobs:
  call-docker-build:
    name: Build and Push Frontend Docker Image
    uses: ./.github/workflows/docker-images-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      service_name: frontend
      build_dir: .
